src/STS.Web/ViewModels/Tickets/BaseTicketViewModel.cs
using System;

namespace STS.Web.ViewModels.Tickets
{
    public class BaseTicketViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string PriorityName { get; set; }

        public string StatusName { get; set; }

        public string AssignedToUserName { get; set; }

        public DateTime CreatedOn { get; set; }
    }
}

src/STS.Web/ViewModels/Tickets/BaseViewModel.cs
namespace STS.Web.ViewModels.Tickets
{
    public class BaseViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

src/STS.Web/ViewModels/Tickets/CommentInputModel.cs
using System.ComponentModel.DataAnnotations;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tickets
{
    public class CommentInputModel
    {
        public int TicketId { get; set; }

        [StringLength(CommentMaxLength, MinimumLength = CommentMinLength)]
        public string Content { get; set; }

        public bool sendEmail { get; set; }
    }
}

src/STS.Web/ViewModels/Tickets/CommentViewModel.cs
namespace STS.Web.ViewModels.Tickets
{
    public class CommentViewModel
    {
        public int Id { get; set; }

        public string Content { get; set; }

        public string UserId { get; set; }

        public string UserUserName { get; set; }

        public string CreatedOn { get; set; }
    }
}

src/STS.Web/ViewModels/Tickets/DepartmentViewModel.cs
namespace STS.Web.ViewModels.Tickets
{
    public class DepartmentViewModel : BaseViewModel
    {
    }
}

src/STS.Web/ViewModels/Tickets/PriorityViewModel.cs
namespace STS.Web.ViewModels.Tickets
{
    public class PriorityViewModel : BaseViewModel
    {
    }
}

src/STS.Web/ViewModels/Tickets/StatusViewModel.cs
namespace STS.Web.ViewModels.Tickets
{
    public class StatusViewModel : BaseViewModel
    {
    }
}

src/STS.Web/ViewModels/Tickets/TicketEditModel.cs
using System.ComponentModel.DataAnnotations;

using STS.Web.Infrastructure.ValidationAttributes;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tickets
{
    public class TicketEditModel
    {
        public int Id { get; set; }

        [StringLength(TitleMaxLength, MinimumLength = TitleMinLength)]
        public string Title { get; set; }

        [StringLength(ContentMaxLength, MinimumLength = ContentMinLength)]
        public string Content { get; set; }

        [StatusId]
        public int? StatusId { get; set; }

        [PriorityId]
        public int? PriorityId { get; set; }

        [DepartmentId]
        public int? DepartmentId { get; set; }

        public string AssignedToId { get; set; }
    }
}

src/STS.Web/ViewModels/Tickets/TicketInputModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using STS.Web.Infrastructure.ValidationAttributes;
using STS.Web.ViewModels.Common;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tickets
{
    public class TicketInputModel
    {
        [Required]
        [StringLength(TitleMaxLength, MinimumLength = TitleMinLength)]
        public string Title { get; set; }

        [Required]
        [StringLength(ContentMaxLength, MinimumLength = ContentMinLength)]
        public string Content { get; set; }

        [PriorityId]
        public int PriorityId { get; set; }

        [DepartmentId]
        public int DepartmentId { get; set; }

        public string AssignedToId { get; set; }

        public IEnumerable<PriorityViewModel> Priorities { get; set; }

        public IEnumerable<StatusViewModel> Statuses { get; set; }

        public IEnumerable<DepartmentViewModel> Departments { get; set; }
    }
}

src/STS.Web/ViewModels/Tickets/TicketViewModel.cs
using System.Collections.Generic;

using STS.Web.ViewModels.Comment;
using STS.Web.ViewModels.Common;
using STS.Web.ViewModels.User;

namespace STS.Web.ViewModels.Tickets
{
    public class TicketViewModel : BaseTicketViewModel
    {
        public string Content { get; set; }

        public int StatusId { get; set; }

        public int DepartmentId { get; set; }

        public string DepartmentName { get; set; }

        public string AssignedToId { get; set; }

        public string EmployeeId { get; set; }

        public string EmployeeUserName { get; set; }

        public string LoggedInUserId { get; set; }

        public int LoggedInUserDepartmentId { get; set; }

        public bool IsOwner => EmployeeId == LoggedInUserId;

        public ICollection<CommentViewModel> Comments { get; set; }

        public ICollection<DepartmentViewModel> Departments { get; set; }

        public ICollection<StatusViewModel> Statuses { get; set; }

        public ICollection<BaseUserViewModel> Employees { get; set; }
    }
}

src/STS.Web/ViewModels/Tickets/TicketsListViewModel.cs
using System;
using System.Collections.Generic;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tickets
{
    public class TicketsListViewModel
    {
        public int TicketsCount { get; set; }

        public int PagesCount => (int)Math.Ceiling(TicketsCount * 1.0 / TicketsPerPage);

        public int Page { get; set; }

        public int PreviousPage => Page - 1;

        public int NextPage => Page + 1;

        public bool HasPreviousPage => Page > 1;

        public bool HasNextPage => Page < PagesCount;

        public string Keyword { get; set; }

        public IEnumerable<BaseTicketViewModel> Tickets { get; set; }
    }
}

src/STS.Web/Areas/Api/Controllers/TicketsController.cs
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;

using STS.Services.Contracts;
using STS.Web.ViewModels.Tickets;

namespace STS.Web.Areas.Api.Controllers
{

    [Route("api/tickets")]
    [ApiController]
    [Authorize]
    public class TicketsController : ControllerBase
    {
        private readonly ITicketService ticketService;
        private readonly IMapper mapper;

        public TicketsController(ITicketService ticketService, IMapper mapper)
        {
            this.ticketService = ticketService;
            this.mapper = mapper;
        }

        [HttpPut]
        public async Task<ActionResult<TicketViewModel>> Edit([FromBody] TicketEditModel ticketDto)
        {
            var ticket = ticketService.GetById(ticketDto.Id);

            if (ticket == null)
            {
                return NotFound();
            }

            var result = await ticketService.EditAsync(ticketDto.Id, ticketDto);
            var response = mapper.Map<TicketViewModel>(result);

            return Ok(response);
        }
    }
}

src/STS.Web/Controllers/TicketsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;

using STS.Data.Models;
using STS.Services.Contracts;
using STS.Web.ViewModels.Tickets;
using STS.Web.ViewModels.User;
using STS.Web.ViewModels.Common;

using static STS.Common.GlobalConstants;

namespace STS.Web.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly ITicketService ticketService;
        private readonly ICommonService commonService;
        private readonly IAdminService adminService;
        private readonly IMapper mapper;
        private readonly UserManager<ApplicationUser> userManager;

        public TicketsController(
            ITicketService ticketService,
            ICommonService commonService,
            IAdminService userService,
            IMapper mapper,
            UserManager<ApplicationUser> userManager)
        {
            this.ticketService = ticketService;
            this.commonService = commonService;
            this.adminService = userService;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Ticket(int id)
        {
            var ticket = ticketService.GetById(id);

            if (ticket == null)
            {
                return NotFound();
            }

            var userId = userManager.GetUserId(User);
            var departmentId = commonService.GetDepartmentId(userId);

            var ticketDto = mapper.Map<TicketViewModel>(ticket);
            ticketDto.Statuses = mapper.Map<List<StatusViewModel>>(commonService.GetStatuses());
            ticketDto.Employees = mapper.Map<List<BaseUserViewModel>>(commonService.GetEmployeesBase(departmentId));
            ticketDto.Departments = mapper.Map<List<DepartmentViewModel>>(commonService.GetDepartmentsBase());
            ticketDto.LoggedInUserId = userId;
            ticketDto.LoggedInUserDepartmentId = commonService.GetDepartmentId(userId);
            return View(ticketDto);
        }

        [HttpGet]
        public IActionResult Tickets(string keyword, int page = DefaultPageNumber)
        {
            var userId = userManager.GetUserId(User);
            var tickets = ticketService.GetAll(userId, page, TicketsPerPage, keyword);

            var ticketsDtos = new TicketsListViewModel
            {
                Page = page,
                Keyword = keyword,
                TicketsCount = ticketService.GetTicketsCount(userId, keyword),
                Tickets = mapper.Map<List<BaseTicketViewModel>>(tickets),
            };

            return View(ticketsDtos);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TicketInputModel ticket)
        {
            if(!ModelState.IsValid)
            {
                return BadRequest();
            }

            var userId = userManager.GetUserId(User);
            await ticketService.CreateAsync(userId, ticket);

            return RedirectToAction(nameof(Tickets), new { keyword = "my"});
        }

        public async Task<IActionResult> Delete(int id)
        {
            var ticket = ticketService.GetById(id);

            if (ticket == null)
            { 
                return NotFound();
            }

            var userId = userManager.GetUserId(User);

            if (ticket.EmployeeId != userId)
            {
                return Unauthorized();
            }

            await ticketService.DeleteAsync(id);

            return RedirectToAction(nameof(Tickets), new { keyword = "my" });
        }
    }
}

src/STS.Web/ViewComponents/CreateTicketViewComponent.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Services.Contracts;
using STS.Web.ViewModels.Common;
using STS.Web.ViewModels.Tickets;

namespace STS.Web.ViewComponents
{
    public class CreateTicketViewComponent : ViewComponent
    {
        private readonly ICommonService commonService;
        private readonly IMapper mapper;

        public CreateTicketViewComponent(ICommonService commonService, IMapper mapper)
        {
            this.commonService = commonService;
            this.mapper = mapper;
        }

        [HttpGet]
        [Authorize]
        public IViewComponentResult Invoke()
        {
            var inputDto = new TicketInputModel
            {
                Priorities = mapper.Map<List<PriorityViewModel>>(commonService.GetPriorities()),
                Departments = mapper.Map<List<DepartmentViewModel>>(commonService.GetDepartmentsBase()),
            };

            return View(inputDto);
        }
    }
}

src/STS.Web/ViewComponents/TasksSideBarViewComponent.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Data.Models;
using STS.Services.Contracts;
using STS.Web.ViewModels.Tasks;

namespace STS.Web.ViewComponents
{
    public class TasksSideBarViewComponent : ViewComponent
    {
        private readonly ITaskService taskService;
        private readonly IMapper mapper;
        private readonly UserManager<ApplicationUser> userManager;

        public TasksSideBarViewComponent(
            ITaskService taskService,
            IMapper mapper, 
            UserManager<ApplicationUser> userManager)
        {
            this.taskService = taskService;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public IViewComponentResult Invoke(bool isManager, int tasksCount)
        {
            var user = Request.HttpContext.User;
            var userId = userManager.GetUserId(user);
            var tasksDtos = taskService.GetSideBarTasks(userId, isManager, tasksCount);

            var tasks = new TasksSideBarViewModel
            {
                Tasks = mapper.Map<IEnumerable<BaseTaskViewModel>>(tasksDtos),
            };

            return View(tasks);
        }
    }
}

src/STS.Web/ViewComponents/TicketsNavBarViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using STS.Data.Models;
using STS.Services.Contracts;

namespace STS.Web.ViewComponents
{
    public class TicketsNavBarViewComponent : ViewComponent
    {
        private readonly ITicketService ticketService;
        private readonly UserManager<ApplicationUser> userManager;

        public TicketsNavBarViewComponent(
            ITicketService ticketService,
            UserManager<ApplicationUser> userManager)
        {
            this.ticketService = ticketService;
            this.userManager = userManager;
        }

        public IViewComponentResult Invoke()
        {
            var user = Request.HttpContext.User;
            var userId = userManager.GetUserId(user);
            var navStatistic = ticketService.GetCategoriesTicketsCount(userId);

            return View(navStatistic);
        }
    }
}

src/STS.Web/Views/Tickets/Ticket.cshtml
@using STS.Web.ViewModels.Tickets;
@using static STS.Common.GlobalConstants;

@model TicketViewModel;
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery

@{
    bool isInLoggedInUserDepartment = Model.LoggedInUserDepartmentId == Model.DepartmentId;
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
    ViewData["requestToken"] = requestToken;
    ViewData["Title"] = Model.Title;
    ViewData["ticketId"] = Model.Id;
}

<section class="ticket-search">
    <div>
        <button class="show-create-btn" title="Create a new ticket...">New Ticket</button>
    </div>
    <div class="search-section">
        <form asp-controller="Tickets" asp-action="Tickets" class="search-ticket-form" method="get">
            <input class="search-input-field"
                   name="keyword"
                   type="text"
                   required
                   minlength=2
                   placeholder="Search..." 
            />
            <button class="search-btn" type="submit">Go</button>
        </form>
    </div>
</section>

<section class="ticket-container">
    <section class="tickets-nav-section">
        <vc:tickets-nav-bar></vc:tickets-nav-bar>
    </section>

    <section class="ticket-wrapper">
        <div class="ticket" data-ticket-id="@Model.Id" data-request-token="@requestToken">
            <div class="ticket-actions">
                <div>
                    <select class="t-status-select"
                            asp-items="@Model.Statuses
                                .Where(x => x.Name != Model.StatusName)
                                .Select(x => new SelectListItem(x.Name, x.Id.ToString()))"
                            disabled="@(!isInLoggedInUserDepartment)"
                    >
                        <option selected="selected" value="@Model.StatusId">@Model.StatusName</option>
                    </select>
                    <select class="t-department-select"
                            asp-items="@Model.Departments
                                .Where(x => x.Name != Model.DepartmentName)
                                .Select(x => new SelectListItem(x.Name, x.Id.ToString()))"
                            disabled="@(!isInLoggedInUserDepartment)"
                    >
                        <option selected="selected" value="@Model.DepartmentId">@Model.DepartmentName</option>
                    </select>
                    <select class="t-employee-select"
                            asp-items="@Model.Employees
                                .Where(x => x.UserName != Model.AssignedToUserName)
                                .Select(x => new SelectListItem(x.UserName, x.Id))"
                            disabled="@(!isInLoggedInUserDepartment)"
                    >
                        <option selected="selected" value="@Model.AssignedToId">@(Model.AssignedToUserName ?? "Select employee")</option>
                    </select>
                </div>
                <div>
                    @if (Model.AssignedToId != Model.LoggedInUserId
                        && Model.LoggedInUserDepartmentId == Model.DepartmentId)
                    {
                        <a href="javascript.void(0)"
                           type="button"
                           class="assign-to-me-btn"
                           data-my-id="@Model.LoggedInUserId">
                                Assign to me
                        </a>
                    }
                    @if (Model.IsOwner &&  Model.LoggedInUserDepartmentId == Model.DepartmentId)
                    {
                        <a asp-controller="Tickets"
                           asp-action="Delete"
                           asp-route-id="@Model.Id"
                           class="t-delete-btn"
                           OnClick=" return ConfirmOnDelete('@deleteTicketMassage')"
                        >
                             <i class="fa fa-trash fa-lg"></i>
                        </a>
                    }
                </div>
            </div>

            <article class="ticket-details">
                <header class="ticket-details-title">
                    <div class="tile-status-priority">
                        <span class="status @Model.StatusName.ToLower().Replace(" ", "")">@Model.StatusName</span>
                        <span class="priority @Model.PriorityName.ToLower().Replace(" ", "")">@Model.PriorityName</span>
                    </div>
                    <div class='t-title-section'>
                        <div class='t-title'>
                            <p class="ticket-title">
                                @Model.Title
                                @if (Model.IsOwner && Model.LoggedInUserDepartmentId == Model.DepartmentId)
                                {
                                    <a class="edit-t-title" href="javascript.void(0)">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                }
                            </p>
                        </div>
                        <div class='t-title-section-edited'></div>
                    </div>
                </header>
                <div class="ticket-body-section">
                    <p class="ticket-content">
                        @Model.Content
                        @if (Model.IsOwner && Model.LoggedInUserDepartmentId == Model.DepartmentId)
                        {
                            <a class="edit-t-content" href="javascript.void(0)">
                                <i class="fa fa-edit"></i>
                            </a>
                        }
                    </p>
                </div>
                <div class="t-content-section-edited"></div>
                <footer class="ticket-footer">
                    <div>
                        <p>
                            from
                            <span class="username">@(Model.EmployeeUserName ?? "Ex employee")</span>
                            created on
                            <span class="date">@Model.CreatedOn</span>
                        </p>
                    </div>
                    <div>
                        <p class="assigned-to-username">
                            <span class="name-prefix">@(Model.AssignedToUserName == null ? "unassigned" : "Assigned to")</span>
                            <span class="username">@(Model.AssignedToUserName == null ? null : Model.AssignedToUserName)</span>
                        </p>
                    </div>
                </footer>
            </article>
        </div>
        <div class="ticket-comments">
            @foreach (var comment in Model.Comments)
            {
                <article class="t-comment">
                    <p>@comment.Content</p>

                    <div class="comment-actions">
                        <div>
                            <span>
                                from
                                <span class="username">@comment.UserUserName</span>
                                on
                                <span class="date">@comment.CreatedOn</span>
                            </span>
                        </div>
                        <div>
                            @if (Model.LoggedInUserId == comment.UserId)
                            {
                                <button class="c-del-btn t-delete-btn"
                                        title="Delete comment."
                                        data-comment-id="@comment.Id"
                                        data-request-token="@requestToken"
                                >
                                    <i class="fa fa-trash"></i>
                                </button>
                            }
                        </div>
                    </div>
                </article>
            }
        </div>
        <div class="new-comment"></div>
        <div class="t-comment-btn-section">
            <button class="t-comment-btn">Comment</button>
        </div>
    </section>
    <aside class="tasks-review">
        <p class="daily-tasks">Daily tasks</p>
        <vc:tasks-side-bar is-manager=false tasks-count=TasksSideBarCount></vc:tasks-side-bar>
    </aside>
</section>

<partial name="_NotificationPartial"></partial>

<section class="create-dialog-overlay">
    <vc:create-ticket></vc:create-ticket>
</section>

<section class="comment-dialog-overlay">
    <partial name="_CommentFormPartial" view-data="ViewData"></partial>
</section>

@section Scripts {
    <script src="~/js/services/confirm-on-delete.js"></script>
    <script type="module" src="~/js/services/tickets-services.js"></script>
    <script type="module" src="~/js/services/create-ticket-validation.js"></script>
    <script type="module" src="~/js/services/comments-ticket-services.js"></script>

}

src/STS.Web/Views/Tickets/Tickets.cshtml
@using Microsoft.JSInterop
@using STS.Web.ViewModels.Tickets;
@using static STS.Common.GlobalConstants;
@model TicketsListViewModel;
@inject IJSRuntime JS

@{
    this.ViewData["Title"] = "Tickets";
    string[] keys = { "my", "to me", "new", "all", "history" };
}

<section class="ticket-search">
    <div>
        <button class="show-create-btn" title="Create a new ticket...">New Ticket</button>
    </div>
    <div class="search-section">
        <form asp-controller="Tickets" asp-action="Tickets" class="search-ticket-form" method="get">
            <input class="search-input-field"
                   name="keyword"
                   type="text"
                   value="@(!keys.Contains(Model.Keyword) ? Model.Keyword : null)"
                   placeholder="Search..."
                   required
                   minlength=2 />
            <button class="search-btn" type="submit">Go</button>
        </form>
    </div>
</section>

<section class="tickets-page-container">
    <section class="tickets-nav-section">
        <vc:tickets-nav-bar></vc:tickets-nav-bar>
    </section>

    <section class="tickets-wrapper">
        <div class="tickets-list">
            @if (Model.TicketsCount > 0)
            {
                <div class="tickets-table">
                    <header class="tickets-table-header">
                        <div class="table-ticket-number">Ticket</div>
                        <div class="table-status">Status</div>
                        <div class="table-priority">Prioriry</div>
                        <div class="table-t-title">Title</div>
                        <div class="table-assigned-to">Assigned to</div>
                        <div class="table-date">Date</div>
                    </header>

                    @foreach (var ticket in Model.Tickets)
                    {
                        <a class="tickets-table-row" asp-action="Ticket" asp-route-id="@ticket.Id" data-ticket-id="@ticket.Id">
                            <div class="ticket-id">@ticket.Id</div>
                            <div>
                                <span class="status @ticket.StatusName.ToLower().Replace(" ", "")">@ticket.StatusName</span>
                            </div>
                            <div>
                                <span class="priority @ticket.PriorityName.ToLower().Replace(" ", "")">@ticket.PriorityName</span>
                            </div>
                            <div class="table-t-title">@(ticket.Title.Length > 80 ? ticket.Title.Substring(0, 80) : ticket.Title)</div>
                            <div>
                                @(ticket.AssignedToUserName == null
                        ? "unassigned"
                        : ticket.AssignedToUserName )
                            </div>
                            <div>@ticket.CreatedOn.ToString("dd/MM/yy")</div>
                        </a>
                    }
                </div>
            }
            else
            {
                <p>No tickets currently available.</p>
            }
        </div>

        @if (Model.PagesCount > 1)
        {
            <nav class="page-nav">
                <ul class="page-nav-list">

                    @if (Model.HasPreviousPage)
                    {
                        <li>
                            <a asp-controller="Tickets" 
                               asp-action="Tickets" 
                               asp-route-page="@Model.PreviousPage" 
                               asp-route-keyword="@Model.Keyword"
                            >
                                    Previous
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Tickets"
                               asp-action="Tickets" 
                               asp-route-page="@(Model.Page - 1)" 
                               asp-route-keyword="@Model.Keyword"
                            >
                                    @(Model.Page - 1)
                            </a>
                        </li>
                    }

                    <li>
                        <a asp-controller="Tickets" 
                           asp-action="Tickets" 
                           asp-route-page="@Model.Page" 
                           asp-route-keyword="@Model.Keyword"
                        >
                                @Model.Page
                        </a>
                    </li>

                    @if (Model.HasNextPage)
                    {
                        <li>
                            <a asp-controller="Tickets"
                               asp-action="Tickets" 
                               asp-route-page="@(Model.Page + 1)" 
                               asp-route-keyword="@Model.Keyword"
                            >
                                    @(Model.Page + 1)
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Tickets" 
                               asp-action="Tickets" 
                               asp-route-page="@Model.NextPage" 
                               asp-route-keyword="@Model.Keyword"
                            >
                                    Next
                            </a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </section>
</section>

<section class="create-dialog-overlay">
    <vc:create-ticket></vc:create-ticket>
</section>

@section Scripts {    
    <script type="module" src="~/js/services/tickets-services.js"></script>
    <script type="module" src="~/js/services/create-ticket-validation.js"></script>
}