src/STS.Web/ViewModels/User/BaseUserInputmodel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using STS.Web.Infrastructure.ValidationAttributes;
using STS.Web.ViewModels.Admin;
using STS.Web.ViewModels.Common;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.User
{
    public class BaseUserInputmodel
    {
        [Required]
        [MaxLength(EmployeeNameMaxLength)]
        [DisplayName("username")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        [MaxLength(EmployeeNameMaxLength)]
        public string Email { get; set; }

        [Required]
        [MaxLength(EmployeeNameMaxLength)]
        [DisplayName("first name")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(EmployeeNameMaxLength)]
        [DisplayName("last name")]
        public string LastName { get; set; }

        [Required]
        [MaxLength(EmployeePositionNameMaxLength)]
        public string Position { get; set; }

        [Required]
        [DisplayName("role")]
        public string Role { get; set; }

        [DepartmentId]
        [DisplayName("department")]
        public int DepartmentId { get; set; }

        public string PhoneNumber { get; set; }

        public IEnumerable<DepartmentViewModel> Departments { get; set; }

        public IEnumerable<RoleViewModel> SystemRoles { get; set; }
    }
}

src/STS.Web/ViewModels/User/BaseUserViewModel.cs
namespace STS.Web.ViewModels.User
{
    public class BaseUserViewModel
    {
        public string Id { get; set; }

        public string UserName { get; set; }
    }
}

src/STS.Web/ViewModels/User/UserEditModel.cs
namespace STS.Web.ViewModels.User
{
    public class UserEditModel : BaseUserInputmodel
    {
        public string Id { get; set; }
    }
}

src/STS.Web/ViewModels/User/UserInputModel.cs
using System.ComponentModel.DataAnnotations;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.User
{
    public class UserInputModel : BaseUserInputmodel
    {
        [Required]
        [StringLength(PasswordMaxLength, MinimumLength = PasswordMinLength)]
        public string Password { get; set; }
    }
}

src/STS.Web/ViewModels/User/UserViewModel.cs
using System.Collections.Generic;

namespace STS.Web.ViewModels.User
{
    public class UserViewModel : BaseUserViewModel
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string FullName => $"{FirstName} {LastName}";

        public string Email { get; set; }

        public string DepartmentName { get; set; }

        public string Position { get; set; }

        public string PhoneNumber { get; set; }

        public bool IsLockedOut { get; set; }

        public IEnumerable<string> Roles { get; set; }
    }
}

src/STS.Web/ViewModels/User/UsersViewModel.cs
using System;
using System.Collections.Generic;

using STS.Web.ViewModels.Common;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.User
{
    public class UsersViewModel
    {
        public string Keyword { get; set; }

        public int? DepartmentId { get; set; }

        public int UsersCount { get; set; }

        public int PagesCount => (int)Math.Ceiling(UsersCount * 1.0 / UsersPerPage);

        public int Page { get; set; }

        public int PreviousPage => Page - 1;

        public int NextPage => Page + 1;

        public bool HasPreviousPage => Page > 1;

        public bool HasNextPage => Page < PagesCount;

        public IEnumerable<UserViewModel> Users { get; set; }

        public IEnumerable<DepartmentViewModel> Departments { get; set; }
    }
}

src/STS.Web/Areas/Administration/Controllers/AdministrationController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;

using STS.Data.Models;
using STS.Services.Contracts;
using STS.Web.ViewModels.Common;
using STS.Web.ViewModels.User;
using STS.Web.Infrastructure.ControllersHelpers.Contracts;

using static STS.Common.GlobalConstants;

namespace STS.Web.Areas.Administration.Controllers
{
    [Authorize(Roles = AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : Controller
    {
        private readonly DateTime lockoutEnd = DateTime.Now.AddYears(100);

        private readonly IAdminService adminService;
        private readonly ICommonService commonService;
        private readonly IMapper mapper;
        private readonly IAdminControllerHelper adminHelper;
        private readonly RoleManager<ApplicationRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(
            IMapper mapper,
            IAdminService adminService,
            ICommonService commonService,
            IAdminControllerHelper adminControllerHelper,
            RoleManager<ApplicationRole> roleManager,
            UserManager<ApplicationUser> userManager)
        {
            this.adminService = adminService;
            this.commonService = commonService;
            this.mapper = mapper;
            this.adminHelper = adminControllerHelper;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Users(int? departmentId, string keyword, int page = DefaultPageNumber)
        {
            var users = adminService.GetUsersAsync(page, keyword, departmentId);
            foreach (var user in users)
            {
                var currUser = await userManager.FindByIdAsync(user.Id);
                user.Roles = await userManager.GetRolesAsync(currUser);
                user.IsLockedOut = await userManager.IsLockedOutAsync(currUser);
            }

            var usersDtos = new UsersViewModel
            {
                Page = page,
                Keyword = keyword,
                DepartmentId = departmentId,
                UsersCount = adminService.GetUsersCount(),
                Users = mapper.Map<IEnumerable<UserViewModel>>(users),
                Departments = mapper.Map<List<DepartmentViewModel>>(commonService.GetDepartmentsBase()),
            };

            return View(usersDtos);
        }

        [HttpGet]
        public IActionResult CreateUser()
        {
            var (departments, roles) = adminHelper.GetDepartmentsAndRoles();
            var user = new UserInputModel
            {
                Departments = departments,
                SystemRoles = roles,
            };

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(UserInputModel user)
        {
            if (!ModelState.IsValid)
            {
                var (departments, roles) = adminHelper.GetDepartmentsAndRoles();
                user.Departments = departments;
                user.SystemRoles = roles;

                return View(user);
            }

            await adminHelper.SignInUser(user);

            return RedirectToAction(nameof(Users));
        }

        public async Task<IActionResult> EditUser(string id)
        {
            var (departments, roles) = adminHelper.GetDepartmentsAndRoles();
            var user = adminService.GetUserById(id);
            var userRoles = await userManager.GetRolesAsync(user);

            var userDto = mapper.Map<UserEditModel>(user);
            userDto.Departments = departments;
            userDto.SystemRoles = roles;
            userDto.Role = string.Join("", userRoles);

            return View(userDto);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserEditModel userInput)
        {
            var erros = await adminHelper.ValidateEmailAndUserName(userInput);

            if (erros.Any())
            {
                foreach (var (key, errorMessage) in erros)
                {
                    ModelState.AddModelError(key, errorMessage);
                }
            }

            if (!ModelState.IsValid)
            {
                var (departments, roles) = adminHelper.GetDepartmentsAndRoles();
                userInput.Departments = departments;
                userInput.SystemRoles = roles;

                return View(userInput);
            }

            var user = await adminService.EditUserAsync(userInput);

            if (userInput.Role != null)
            {
                await adminHelper.EditUserRole(userInput.Role, user);
            }

            return RedirectToAction(nameof(Users));
        }

        public async Task<IActionResult> LockoutUser(string id)
        {
            var user = adminService.GetUserById(id);

            if (user == null)
            {
                return BadRequest();
            }

            await userManager.SetLockoutEnabledAsync(user, true);
            await userManager.SetLockoutEndDateAsync(user, lockoutEnd);
            await userManager.UpdateAsync(user);

            return RedirectToAction(nameof(Users));
        }

        public async Task<IActionResult> UnlockUser(string id)
        {
            var user = adminService.GetUserById(id);

            if (user == null)
            {
                return BadRequest();
            }

            await userManager.SetLockoutEndDateAsync(user, DateTime.Now);
            await userManager.UpdateAsync(user);

            return RedirectToAction(nameof(Users));
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = adminService.GetUserById(id);

            if (user == null)
            {
                return BadRequest();
            }

            await adminService.DeleteUserAsync(id);

            return RedirectToAction(nameof(Users));
        }

        [HttpPost]
        public async Task<IActionResult> CreateDepartment([StringLength(DepartmentNameMaxLength, MinimumLength = DepartmentNameMinLength)]  string departmentName)
        {
            if (ModelState.IsValid)
            {
                await adminService.CreateDepartmentAsync(departmentName);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole([StringLength(RoleNameMaxLength, MinimumLength = RoleNameMinLength)] string roleName)
        {
            var role = await roleManager.FindByNameAsync(roleName);

            if (!ModelState.IsValid || role != null)
            {
                return RedirectToAction(nameof(Index));
            }

            await roleManager.CreateAsync(new ApplicationRole(roleName));

            return RedirectToAction(nameof(Index));
        }
    }
}

src/STS.Web/Areas/Api/Controllers/UsersController.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Services.Contracts;
using STS.Web.ViewModels.User;
using System.Threading.Tasks;

namespace STS.Web.Areas.Api.Controllers
{
    [Route("api/users")]
    [ApiController]
    [Authorize]
    public class UsersController : ControllerBase
    {
        private readonly ICommonService commonService;
        private readonly IMapper mapper;

        public UsersController(ICommonService commonService, IMapper mapper)
        {
            this.commonService = commonService;
            this.mapper = mapper;
        }

        [HttpGet("{departmentId:int}")]
        public async Task<ActionResult<BaseUserViewModel>> GetEmployees(int departmentId)
        {
            bool isExisting = await commonService.IsDepartmentExisting(departmentId);
            if (!isExisting)
            {
                return BadRequest();
            }

            var employees = mapper.Map<IEnumerable<BaseUserViewModel>>(commonService.GetEmployeesBase(departmentId));

            return Ok(employees);
        }
    }
}

src/STS.Web/ViewComponents/DepartmentsViewComponent.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Services.Contracts;
using STS.Web.ViewModels.Admin;

namespace STS.Web.ViewComponents
{
    public class DepartmentsViewComponent : ViewComponent
    {
        private readonly ICommonService commonService;
        private readonly IMapper mapper;

        public DepartmentsViewComponent(ICommonService commonService, IMapper mapper)
        {
            this.commonService = commonService;
            this.mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            var departmentsDto = commonService.GetDepartmentsWithStatistic();
            var departments = mapper.Map<IEnumerable<DepartmentStatisticViewModel>>(departmentsDto);

            return View(departments);
        }
    }
}

src/STS.Web/ViewComponents/RolesViewComponent.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Services.Contracts;
using STS.Web.ViewModels.Admin;

namespace STS.Web.ViewComponents
{
    public class RolesViewComponent : ViewComponent
    {
        private readonly ICommonService commonService;
        private readonly IMapper mapper;

        public RolesViewComponent(ICommonService commonService, IMapper mapper)
        {
            this.commonService = commonService;
            this.mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            var rolesDto = commonService.GetRoles();
            var roles = mapper.Map<IEnumerable<RoleViewModel>>(rolesDto);

            return View(roles);
        }
    }
}

src/STS.Web/ViewComponents/TicketsStatisticViewComponent.cs
using Microsoft.AspNetCore.Mvc;

using STS.Services.Contracts;

namespace STS.Web.ViewComponents
{
    public class TicketsStatisticViewComponent : ViewComponent
    {
        private readonly ICommonService commonService;

        public TicketsStatisticViewComponent(ICommonService commonService)
        {
            this.commonService = commonService;
        }

        public IViewComponentResult Invoke()
        {
            var departmentsDto = commonService.GetTicketsStatistic();

            return View(departmentsDto);
        }
    }
}

src/STS.Web/Areas/Administration/Views/Administration/CreateUser.cshtml
@using STS.Web.ViewModels.User
@model UserInputModel

<section class="create-user">
    <form class="create-user-form" asp-controller="Administration" asp-action="CreateUser" method="post">
        <div class="user-select-group">
            <div>
                <label asp-for="Role">Role:</label>
                <select asp-for="Role"                                    
                        asp-items="Model.SystemRoles
                            .Select(t => new SelectListItem(t.Name, t.Name))"
                        required
                >
                    <option value="" selected>Please select</option>
                </select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="DepartmentId">Department:</label>
                <select asp-for="DepartmentId"
                        asp-items="Model.Departments
                            .Select(t => new SelectListItem(t.Name, t.Id.ToString()))"
                        required
                >
                    <option value="" selected>Please select</option>
                </select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
        </div>
        <div class="inputs-div"> 
            <div>
                <label asp-for="UserName">Username:</label>
                <input asp-for="UserName">
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Email">Email:</label>
                <input asp-for="Email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Password">Password:</label>
                <input asp-for="Password">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="FirstName">First name:</label>
                <input asp-for="FirstName">
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="LastName">Last name:</label>
                <input asp-for="LastName">
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Position">Position:</label>
                <input asp-for="Position">
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PhoneNumber">Phone number:</label>
                <input asp-for="PhoneNumber">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div>
            <button class="show-create-btn" type="submit">Register</button>
        </div>
    </form>
</section>

src/STS.Web/Areas/Administration/Views/Administration/EditUser.cshtml
@using STS.Web.ViewModels.User

@model UserEditModel

<section class="create-user">
    <form class="create-user-form" asp-controller="Administration" asp-action="EditUser" method="post">
        <input type="hidden" asp-for="Id" value="@Model.Id"/>
        <div class="user-select-group">
            <div>
                <label asp-for="Role">Role:</label>
                <select asp-for="Role"                                    
                        asp-items="Model.SystemRoles
                    .Select(t => new SelectListItem(t.Name, t.Name))">
                    <option value="" selected>Please select</option>
                </select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="DepartmentId">Department:</label>
                <select asp-for="DepartmentId"
                        asp-items="Model.Departments
                    .Select(t => new SelectListItem(t.Name, t.Id.ToString()))">
                    <option value="" selected>Please select</option>
                </select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
        </div>
        <div class="inputs-div"> 
            <div>
                <label asp-for="UserName">Username:</label>
                <input asp-for="UserName">
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Email">Email:</label>
                <input asp-for="Email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="FirstName">First name:</label>
                <input asp-for="FirstName">
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="LastName">Last name:</label>
                <input asp-for="LastName">
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Position">Position:</label>
                <input asp-for="Position">
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PhoneNumber">Phone number:</label>
                <input asp-for="PhoneNumber">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div>
            <button class="show-create-btn" type="submit">Confirm</button>
        </div>
    </form>
</section>

src/STS.Web/Areas/Administration/Views/Administration/Index.cshtml
@{
    this.ViewData["Title"] = "Admin panel";
}

<h3 class="admin-greeting">Welcome to Admin panel</h3>

<section class="admin-wrapper">
    <article class="admin-stat-section">
        <h5 class="t-stat-title">Tickets statistic</h5>
        <vc:tickets-statistic></vc:tickets-statistic>
    </article>
    <div class="admin-users-row">
        <article class="admin-dep-article">
            <h5 class="dep-title">Departments</h5>
            <vc:departments></vc:departments>
        </article>
        <article class="admin-roles-section">
            <h5 class="t-stat-title">Roles</h5>
            <vc:roles></vc:roles>
        </article>
        <article class="admin-user-section">
            <h5 class="user-title">Users</h5>
            <a class="create-user-btn" asp-controller="Administration" asp-action="CreateUser">
                Create user
            </a>
            <a class="users-btn" asp-controller="Administration" asp-action="Users">
                Users Explorer
            </a>
        </article>
    </div>
</section>

src/STS.Web/Areas/Administration/Views/Administration/Users.cshtml
@using STS.Web.ViewModels.User;

@using static STS.Common.GlobalConstants;

@model UsersViewModel;

@{
    ViewData["Title"] = "Users";
}

<div class="admin-users">
    <section class="user-search-section">
        <form method="get" asp-controller="Administration" asp-action="Users" class="manager-search-form">
             <section class="p-select">
                <select class="form-control-sm t-employee-select"
                        for="DepartmentId"
                        name="DepartmentId"
                        asp-items="Model.Departments.Select(x => new SelectListItem(x.Name, x.Id.ToString()))">
                    <option value="" selected="selected">Please select</option>
                </select>
            </section>
            <section class="user-s-inpit-btn-sec">
                <input name="keyword"
                       type="text"
                       value="@(Model.Keyword != null ? Model.Keyword : null)"
                       class="search-input-field"
                       placeholder="Search..."
                >
                <button class="tasks-search-btn" type="submit">Go</button>
            </section>
        </form>
    </section>

    <section class="users-table">
        <header class="users-talbe-header">
            <div>Username</div>
            <div>Email</div>
            <div>Full Name</div>
            <div>Department</div>
            <div>Position</div>
            <div>Roles</div>
            <div>Phone Number</div>
            <div></div>
        </header>

        @foreach (var user in Model.Users)
        {
            <div class="user-row">
                <div>@user.UserName</div>
                <div>@user.Email</div>
                <div>@user.FullName</div>
                <div>@user.DepartmentName</div>
                <div>@user.Position</div>
                <div>@string.Join(", ", user.Roles)</div>
                <div>@user.PhoneNumber</div>
                <div>
                    <a class="user-edit-btn" 
                       title="Edit user data" 
                       asp-controller="Administration" 
                       asp-action="EditUser" 
                       asp-route-id="@user.Id"
                    >
                        <i class="fa fa-edit"></i>
                    </a>
                    @if (user.IsLockedOut)
                    {
                        <a class="user-lockout-btn" 
                           title="Unlock user" 
                           asp-controller="Administration" 
                           asp-action="UnlockUser" 
                           asp-route-id="@user.Id"
                        >
                            <i class="fa fa-unlock"></i>
                        </a>
                    }
                    else
                    {
                        <a class="user-lockout-btn" 
                           title="Lockout user" 
                           asp-controller="Administration" 
                           asp-action="LockoutUser" 
                           asp-route-id="@user.Id"
                        >
                            <i class="fa fa-ban"></i>
                        </a>
                    }
                    <a class="user-delete-btn"
                       title="Delete user" 
                       asp-controller="Administration" 
                       asp-action="DeleteUser" 
                       asp-route-id="@user.Id" 
                       OnClick=" return ConfirmOnDelete('@deleteUserMassage')"
                    >
                        <i class="fa fa-trash"></i>
                    </a>
                </div>
            </div>
        }
    </section>
    <section class="pagination">
        @if (Model.PagesCount > 1)
        {
            <nav class="page-nav">
                <ul class="page-nav-list">

                    @if (Model.HasPreviousPage)
                    {
                        <li>
                            <a asp-controller="Administration"
                               asp-action="Users"
                               asp-route-page="@Model.PreviousPage"
                               asp-route-keyword="@Model.Keyword"
                               asp-route-departmentId="@Model.DepartmentId"
                            >
                                Previous
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Administration"
                               asp-action="Users"
                               asp-route-page="@(Model.Page - 1)"
                               asp-route-keyword="@Model.Keyword"
                               asp-route-departmentId="@Model.DepartmentId"                           
                            >
                                @(Model.Page - 1)
                            </a>
                        </li>
                    }

                    <li>
                        <a asp-controller="Administration"
                           asp-action="Users"
                           asp-route-page="@Model.Page"
                           asp-route-keyword="@Model.Keyword"
                           asp-route-departmentId="@Model.DepartmentId"
                        >
                            @Model.Page
                        </a>
                    </li>

                    @if (Model.HasNextPage)
                    {
                        <li>
                            <a asp-controller="Administration"
                               asp-action="Users"
                               asp-route-page="@(Model.Page + 1)"
                               asp-route-keyword="@Model.Keyword"
                               asp-route-departmentId="@Model.DepartmentId"
                            >
                                @(Model.Page + 1)
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Administration"
                               asp-action="Users"
                               asp-route-page="@Model.NextPage"
                               asp-route-keyword="@Model.Keyword"
                               asp-route-departmentId="@Model.DepartmentId"
                            >
                                Next
                            </a>
                        </li>
                    }

                </ul>
            </nav>
        }
    </section>
</div>

@section Scripts{
    <script src="~/js/services/confirm-on-delete.js"></script>
}