src/STS.Web/ViewModels/Tasks/BaseTaskViewModel.cs
using System;

namespace STS.Web.ViewModels.Tasks
{
    public class BaseTaskViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public DateTime Deadline { get; set; }

        public string PriorityName { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/ManagerTaskSearchViewModel.cs
using System.Collections.Generic;

using STS.Web.ViewModels.User;

namespace STS.Web.ViewModels.Tasks
{
    public class ManagerTaskSearchViewModel
    {
        public string Keyword { get; set; }

        public IEnumerable<BaseUserViewModel> Employees { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/ReplayTaskInputModel.cs
using System.ComponentModel.DataAnnotations;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tasks
{
    public class ReplayTaskInputModel
    {
        public int EmployeeTaskId { get; set; }

        [Required]
        [StringLength(ReplyTaskContentMaxLength, MinimumLength = ReplyTaskContentMinLength)]
        public string Content { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/ReplayTaskViewModel.cs
namespace STS.Web.ViewModels.Tasks
{
    public class ReplayTaskViewModel
    {
        public int id { get; set; }

        public string Content { get; set; }

        public string UserUserName { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/ReplyTaskInputModel.cs
using System.ComponentModel.DataAnnotations;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tasks
{
    public class ReplyTaskInputModel
    {
        public int EmployeeTaskId { get; set; }

        [Required]
        [StringLength(ReplyTaskContentMaxLength, MinimumLength = ReplyTaskContentMinLength)]
        public string Content { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/ReplyTaskViewModel.cs
namespace STS.Web.ViewModels.Tasks
{
    public class ReplyTaskViewModel
    {
        public int Id { get; set; }

        public string Content { get; set; }

        public string UserUserName { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/SideBarTasksViewModel.cs
using System.Collections.Generic;

namespace STS.Web.ViewModels.Tasks
{
    public class SideBarTasksViewModel
    {
        public IEnumerable<BaseTaskViewModel> Tasks { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/TaskEditModel.cs
using System;
using System.ComponentModel.DataAnnotations;

using STS.Web.Infrastructure.ValidationAttributes;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tasks
{
    public class TaskEditModel
    {
        public int Id { get; set; }

        [StringLength(TitleMaxLength, MinimumLength = TitleMinLength)]
        public string Title { get; set; }

        [StringLength(TaskDescriptionMaxLength, MinimumLength = TaskDescriptionMinLength)]
        public string Description { get; set; }

        [Deadline]
        public DateTime? Deadline { get; set; }

        [PriorityId]
        public int? PriorityId { get; set; }

        [StatusId]
        public int? StatusId { get; set; }

        public string EmployeeId { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/TaskInputModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using STS.Web.Infrastructure.ValidationAttributes;
using STS.Web.ViewModels.Common;
using STS.Web.ViewModels.User;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tasks
{
    public class TaskInputModel
    {
        [Required]
        [StringLength(TitleMaxLength, MinimumLength = TitleMinLength)]
        public string Title { get; set; }

        [Required]
        [StringLength(TaskDescriptionMaxLength, MinimumLength = TaskDescriptionMinLength)]
        public string Description { get; set; }

        [Deadline]
        public DateTime Deadline { get; set; }

        [PriorityId]
        public int PriorityId { get; set; }

        [Required]
        public string EmployeeId { get; set; }

        public IEnumerable<PriorityViewModel> Priorities { get; set; }

        public IEnumerable<BaseUserViewModel> Employees { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/TaskLinstingViewModel.cs
namespace STS.Web.ViewModels.Tasks
{
    public class TaskLinstingViewModel : BaseTaskViewModel
    {
        public string EmployeeUserName  { get; set; }

        public string ManagerUserName { get; set; }

        public string StatusName { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/TaskViewModel.cs
using System.Collections.Generic;

using STS.Web.ViewModels.Common;
using STS.Web.ViewModels.User;

namespace STS.Web.ViewModels.Tasks
{
    public class TaskViewModel : TaskLinstingViewModel
    {
        public string Description { get; set; }

        public string ManagerId { get; set; }

        public string EmployeeId { get; set; }

        public IEnumerable<StatusViewModel> Statuses { get; set; }

        public IEnumerable<BaseUserViewModel> Employees { get; set; }

        public IEnumerable<ReplyTaskViewModel> Comments { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/TasksSideBarViewModel.cs
using System.Collections.Generic;

namespace STS.Web.ViewModels.Tasks
{
    public class TasksSideBarViewModel
    {
        public IEnumerable<BaseTaskViewModel> Tasks { get; set; }
    }
}

src/STS.Web/ViewModels/Tasks/TasksViewModel.cs
using System;
using System.Collections.Generic;

using static STS.Common.GlobalConstants;

namespace STS.Web.ViewModels.Tasks
{
    public class TasksViewModel
    {

        public int TasksCount { get; set; }

        public int PagesCount => (int)Math.Ceiling(TasksCount * 1.0 / TasksPerPage);

        public int Page { get; set; }

        public int PreviousPage => Page - 1;

        public int NextPage => Page + 1;

        public bool HasPreviousPage => Page > 1;

        public bool HasNextPage => Page < PagesCount;

        public bool OnlyActive { get; set; }

        public string Keyword { get; set; }

        public string EmployeeId { get; set; }

        public string ManagerId { get; set; }
  
        public IEnumerable<TaskLinstingViewModel> Tasks { get; set; }
    }
}

src/STS.Web/Areas/Api/Controllers/TasksController.cs
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Services.Contracts;
using STS.Web.ViewModels.Tasks;

namespace STS.Web.Areas.Api.Controllers
{
    [Route("api/tasks")]
    [ApiController]
    [Authorize]
    public class TasksController : ControllerBase
    {
        private readonly ITaskService taskServie;
        private readonly IMapper mapper;

        public TasksController(ITaskService taskServie, IMapper mapper)
        {
            this.taskServie = taskServie;
            this.mapper = mapper;
        }

        [HttpPut]
        public async Task<ActionResult<TaskViewModel>> Edit([FromBody] TaskEditModel taskDto)
        {
            if (!ModelState.IsValid)
            { 
                return BadRequest();
            }

            var task = taskServie.GetById(taskDto.Id);

            if (task == null)
            {
                return NotFound();
            }

            var result = await taskServie.EditAsync(taskDto);
            var response = mapper.Map<TaskViewModel>(result);

            return Ok(response);
        }
    }
}

src/STS.Web/Controllers/TasksController.cs
using System.Collections.Generic;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Data.Models;
using STS.Services.Contracts;
using STS.Web.ViewModels.Tasks;
using STS.Web.ViewModels.Common;
using STS.Web.ViewModels.User;

using static STS.Common.GlobalConstants;

namespace STS.Web.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private readonly IMapper mapper;
        private readonly ITaskService taskService;
        private readonly ICommonService commonService;
        private readonly UserManager<ApplicationUser> userManager;

        public TasksController(
            IMapper mapper,
            ITaskService taskService,
            ICommonService commonService,
            UserManager<ApplicationUser> userManager)
        {
            this.mapper = mapper;
            this.taskService = taskService;
            this.commonService = commonService;
            this.userManager = userManager;
        }

        public IActionResult Task(int id)
        {
            var currUserId = userManager.GetUserId(User);
            var taskDto = taskService.GetById(id);

            if (taskDto == null)
            {
                return BadRequest();
            }

            if (taskDto.EmployeeId != currUserId
                && !User.IsInRole(ManagerRoleName)
                && !User.IsInRole(AdministratorRoleName)) 
            {
                return Unauthorized();
            }

            var task = mapper.Map<TaskViewModel>(taskDto);
            task.Statuses = mapper.Map<List<StatusViewModel>>(commonService.GetStatuses());

            if (User.IsInRole(ManagerRoleName) 
               || User.IsInRole(AdministratorRoleName)) 
            {
                var departmentId = commonService.GetDepartmentId(currUserId);
                task.Employees = mapper.Map<List<BaseUserViewModel>>(commonService.GetEmployeesBase(departmentId));
            }

            return View(task);
        }

        public IActionResult Index(
            string keyword,
            bool isActive, 
            int page = DefaultPageNumber)
        {
            var tasks = PrepareViewModel(false, keyword, isActive, null, page);

            return View(tasks);
        }

        [Authorize(Roles = "Administrator, Manager")]
        public IActionResult Management(
            string keyword, 
            bool isActive, 
            string employeeId, 
            int page = DefaultPageNumber)
        {
            var tasks = PrepareViewModel(true, keyword, isActive, employeeId, page);

            return View(tasks);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(TaskInputModel taskInput)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var userId = userManager.GetUserId(User);
            await taskService.CreateAsync(userId, taskInput);

            return RedirectToAction(nameof(Management));
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Delete(int id)
        {
            var task = taskService.GetById(id);
            var userId = userManager.GetUserId(User);

            if (task == null)
            {
                return BadRequest();
            }

            if (task.ManagerId != userId) 
            {
                return Unauthorized();
            }

            await taskService.DeleteAsync(id);

            return RedirectToAction(nameof(Management));
        }

        private TasksViewModel PrepareViewModel(
            bool isManager,
            string keyword,
            bool isActive,
            string employeeId,
            int page)
        {
            var currUserId = userManager.GetUserId(User);
            var tasksDtos = taskService.GetAll(currUserId, isManager, isActive, page, keyword, employeeId);

            var tasksDto = new TasksViewModel
            {
                Keyword = keyword,
                OnlyActive = isActive,
                Page = page,
                TasksCount = taskService.GetCount(),
                Tasks = mapper.Map<List<TaskLinstingViewModel>>(tasksDtos),
            };

            if (isManager)
            {
                tasksDto.EmployeeId = employeeId;
                tasksDto.ManagerId = currUserId;
            }

            return tasksDto;
        }
    }
}

src/STS.Web/ViewComponents/CreateTaskViewComponent.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Data.Models;
using STS.Services.Contracts;
using STS.Web.ViewModels.Common;
using STS.Web.ViewModels.Tasks;
using STS.Web.ViewModels.User;

namespace STS.Web.ViewComponents
{
    public class CreateTaskViewComponent : ViewComponent
    {
        private readonly ICommonService commonService;
        private readonly IMapper mapper;
        private readonly UserManager<ApplicationUser> userManager;

        public CreateTaskViewComponent(
            ICommonService commonService,
            IMapper mapper,
            UserManager<ApplicationUser> userManager)
        {
            this.commonService = commonService;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public IViewComponentResult Invoke()
        {
            var user = Request.HttpContext.User;
            var userId = userManager.GetUserId(user);
            var departmentId = commonService.GetDepartmentId(userId);

            var inputModel = new TaskInputModel
            {
                Priorities = mapper.Map<List<PriorityViewModel>>(commonService.GetPriorities()),
                Employees = mapper.Map<IEnumerable<BaseUserViewModel>>(commonService.GetEmployeesBase(departmentId)),
            };

            return View(inputModel);
        }
    }
}

src/STS.Web/ViewComponents/ManagementTaskSearchViewComponent.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Services.Contracts;
using STS.Web.ViewModels.User;
using STS.Web.ViewModels.Tasks;

namespace STS.Web.ViewComponents
{
    public class ManagementTaskSearchViewComponent : ViewComponent
    {
        private readonly IMapper mapper;
        private readonly ICommonService commonService;

        public ManagementTaskSearchViewComponent(IMapper mapper, ICommonService commonService)
        {
            this.mapper = mapper;
            this.commonService = commonService;
        }

        public IViewComponentResult Invoke(string keyword, string managerId)
        {
            var departmentId = commonService.GetDepartmentId(managerId);

            var employees = mapper.Map<IEnumerable<BaseUserViewModel>>(
                               commonService.GetEmployeesBase(departmentId));

            var searchModel = new ManagerTaskSearchViewModel
            {
                Keyword = keyword,
                Employees = employees,
            };

            return View(searchModel);        
        }
    }
}

src/STS.Web/ViewComponents/TasksSideBarViewComponent.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;

using STS.Data.Models;
using STS.Services.Contracts;
using STS.Web.ViewModels.Tasks;

namespace STS.Web.ViewComponents
{
    public class TasksSideBarViewComponent : ViewComponent
    {
        private readonly ITaskService taskService;
        private readonly IMapper mapper;
        private readonly UserManager<ApplicationUser> userManager;

        public TasksSideBarViewComponent(
            ITaskService taskService,
            IMapper mapper, 
            UserManager<ApplicationUser> userManager)
        {
            this.taskService = taskService;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public IViewComponentResult Invoke(bool isManager, int tasksCount)
        {
            var user = Request.HttpContext.User;
            var userId = userManager.GetUserId(user);
            var tasksDtos = taskService.GetSideBarTasks(userId, isManager, tasksCount);

            var tasks = new TasksSideBarViewModel
            {
                Tasks = mapper.Map<IEnumerable<BaseTaskViewModel>>(tasksDtos),
            };

            return View(tasks);
        }
    }
}

src/STS.Web/Views/Tasks/Index.cshtml
@using STS.Web.ViewModels.Tasks;

@model TasksViewModel;

@{
    this.ViewData["Title"] = "My tasks";
    this.ViewData["Keyword"] = @Model.Keyword;
}

<div class="tasks-wrapper">
    <partial name="_TaskSideBar" view-data="this.ViewData" />

    <section class="tasks-table-wrapper">
        <partial name="_TasksTable" model="Model"/>

        <div class="pagination">
            @if (Model.PagesCount > 1)
            {
                <nav class="page-nav">
                    <ul class="page-nav-list">
                        @if (Model.HasPreviousPage)
                        {
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Index"
                                   asp-route-page="@Model.PreviousPage"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                            Previous
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Index"
                                   asp-route-page="@(Model.Page - 1)"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                            @(Model.Page - 1)
                                </a>
                            </li>
                        }

                        <li>
                            <a asp-controller="Tasks"
                               asp-action="Index"
                               asp-route-page="@Model.Page"
                               asp-route-isActive="@Model.OnlyActive"
                               asp-route-keyword="@Model.Keyword"
                            >
                                    @Model.Page
                            </a>
                        </li>

                        @if (Model.HasNextPage)
                        {
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Index"
                                   asp-route-page="@(Model.Page + 1)"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                            @(Model.Page + 1)
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Index"
                                   asp-route-page="@Model.NextPage"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                            Next
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
            }
        </div>
    </section>
</div>

src/STS.Web/Views/Tasks/Management.cshtml
@using STS.Web.ViewModels.Tasks;
@model TasksViewModel;

@{
    this.ViewData["Title"] = "Tasks management";
}

<div class="m-tasks-wrapper">
    <section class="tasks-side-bar-section">
        <div class="m-panel-wrapper"> 
            <section>
                <button class="create-task-btn management" title="Create a new task...">New Task</button>
            </section>
            <vc:management-task-search keyword="@Model.Keyword" manager-id="@Model.ManagerId"></vc:management-task-search>
        </div>
        <vc:tasks-side-bar is-manager=true tasks-count=TasksSideBarCount></vc:tasks-side-bar>
    </section>

    <section class="tasks-table-wrapper">

        <partial name="_TasksTable" model="Model" />

        <div class="pagination">
            @if (Model.PagesCount > 1)
            {
                <nav class="page-nav">
                    <ul class="page-nav-list">

                        @if (Model.HasPreviousPage)
                        {
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Management"
                                   asp-route-page="@Model.PreviousPage"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                    Previous
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Management"
                                   asp-route-page="@(Model.Page - 1)"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                    @(Model.Page - 1)
                                </a>
                            </li>
                        }

                        <li>
                            <a asp-controller="Tasks"
                               asp-action="Management"
                               asp-route-page="@Model.Page"
                               asp-route-isActive="@Model.OnlyActive"
                               asp-route-keyword="@Model.Keyword"
                            >
                                @Model.Page
                            </a>
                        </li>

                        @if (Model.HasNextPage)
                        {
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Management"
                                   asp-route-page="@(Model.Page + 1)"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                    @(Model.Page + 1)
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Tasks"
                                   asp-action="Management"
                                   asp-route-page="@Model.NextPage"
                                   asp-route-isActive="@Model.OnlyActive"
                                   asp-route-keyword="@Model.Keyword"
                                >
                                    Next
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
            }
        </div>

    </section>

</div>

<partial name="_NotificationPartial"></partial>

<section class="create-task-overlay">
    <vc:create-task></vc:create-task>
</section>

@section Scripts {
    <script type="module" src="~/js/services/show-create-task-dialog.js"></script>
    <script type="module" src="~/js/services/create-task-validation.js"></script>
} 

src/STS.Web/Views/Tasks/Task.cshtml
@using System.Security.Claims;
@using STS.Web.ViewModels.Tasks;
@using STS.Web.ViewModels.Common;

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@model TaskViewModel;

@{
    this.ViewData["Title"] = "Task details";
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
    bool isManager = User.IsInRole(AdministratorRoleName) || User.IsInRole(ManagerRoleName);
    string currUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
    bool isOwnTask = Model.ManagerId == currUserId;

    Func<StatusViewModel, bool> statusFilter = status =>
    {
        if (!isManager)
        {
            return (status.Name.ToLower() != Model.StatusName.ToLower()) && status.Name.ToLower() != "closed";
        }

        return status.Name.ToLower() != Model.StatusName.ToLower();
    };
}

<section class="task-wrapper">
    <partial name="_TaskSideBar" view-data=null />

    <section class="task-details" data-task-id="@Model.Id" data-request-token="@requestToken">
        <section class="task-actions">
            <div>
                <select class="task-status-select"
                        asp-items="@Model.Statuses
                                .Where(statusFilter)
                                .Select(x => new SelectListItem(x.Name, x.Id.ToString()))"
                        disabled="@(!isManager && (Model.StatusName.ToLower() == "closed") ? true : false)"
                >
                    <option class="status"
                            selected="selected"
                            value="@(Model.Statuses
                                          .Where(x => x.Name.ToLower() == Model.StatusName.ToLower())
                                          .Select(x => x.Id)
                                          .FirstOrDefault())"
                    >
                        @Model.StatusName
                    </option>
                </select>

                @if (isManager && isOwnTask)
                {
                    <select class="t-employee-select"
                            asp-items="@Model.Employees
                                    .Where(x => x.UserName != Model.EmployeeUserName)
                                    .Select(x => new SelectListItem(x.UserName, x.Id))"
                    >
                        <option selected="selected" value="@Model.EmployeeId">@Model.EmployeeUserName</option>
                    </select>
                }
            </div>
            @if (isManager && isOwnTask)
            {
                <div class="delete-btn-div">
                    <a asp-controller="Tasks"
                       asp-action="Delete"
                       asp-route-id="@Model.Id"
                       class="t-delete-btn"
                       OnClick=" return ConfirmOnDelete('@deleteTaskMassage')"
                    >
                        <i class="fa fa-trash fa-lg"></i>
                    </a>
                </div>
            }
        </section>

        <section class="task-info">
            <div class="task-s-p-d">
                <p class="status @Model.StatusName.Replace(" ", "").ToLower()">@Model.StatusName</p>
                <p class="priority @Model.PriorityName.Replace(" ", "").ToLower()">@Model.PriorityName</p>
                <p class="deadline">@Model.Deadline</p>
            </div>
            <div>
                <h5>@Model.Title</h5>
                <p>@Model.Description</p>
                <p class="task-manager username"><span class="from-user">from</span> @Model.ManagerUserName</p>
            </div>
        </section>
    </section>

    <partial name="_TaskComments" model="Model"></partial>
</section>

<partial name="_NotificationPartial"></partial> 

@section Scripts{
    <script src="~/js/services/confirm-on-delete.js"></script>
    <script type="module" src="~/js/services/tasks-services.js"></script>
}

src/STS.Web/Views/Tasks/_TaskSideBar.cshtml
@{
    string keyWords = this.ViewData["Keyword"] as string;
}

<section class="tasks-side-bar-section">
    <div class="search-task-section">
        <form method="post" asp-controller="Tasks" asp-action="Index">
            <div class="search-input-btn-sec">
                <input name="keyword"
                       type="text"
                       value="@(keyWords == null ? null : keyWords)"
                       class="search-input-field"
                       placeholder="Search..." 
                />
                 <button type="submit" class="tasks-search-btn">Go</button>
            </div>
            <div class="checkbox-btn-sec tasks">
                <div class="switch-box">
                    <label class="switch">
                        <input id="isActive" type="checkbox" name="isActive" value="true">
                        <span class="slider round"></span>
                    </label>
                    <label class="checkbox-label" for="isActive"> Only active</label>
                </div>
            </div>
        </form>
    </div>

    <vc:tasks-side-bar is-manager=false tasks-count=TasksSideBarCount></vc:tasks-side-bar>
</section>

src/STS.Web/Views/Tasks/_TasksTable.cshtml
@{
    bool isManager = User.IsInRole(AdministratorRoleName) || User.IsInRole(ManagerRoleName);
    var actionKvp = this.Context.Request.RouteValues.FirstOrDefault(x => x.Key == "action");
    var isManagementAction = actionKvp.Value.ToString() == "Management";
}

<section class="tasks-table">
    @if (Model.TasksCount > 0)
    {
        <div class="tickets-table">
            <header class="tickets-table-header">
                <div class="table-task-number">Task</div>
                <div class="table-status">Status</div>
                <div class="table-priority">Prioriry</div>
                <div class="table-t-title">Title</div>
                <div class="table-assigned-to">Employee</div>
                <div class="task-deadline">Deadline</div>
            </header>

            @foreach (var task in Model.Tasks)
            {
                <a class="tickets-table-row"
                   asp-controller="Tasks"
                   asp-action="Task"
                   asp-route-id="@task.Id"
                >
                    <div>@task.Id</div>
                    <div>
                        <span class="status @task.StatusName.ToLower().Replace(" ", "")">@task.StatusName</span>
                    </div>
                    <div>
                        <span class="priority @task.PriorityName.ToLower().Replace(" ", "")">@task.PriorityName</span>
                    </div>
                    <div class="table-t-title">@task.Title</div>
                    <div>
                        @(isManager && isManagementAction 
                            ? task.EmployeeUserName 
                            : task.ManagerUserName) 
                    </div>
                    <div>@task.Deadline.ToString("dd/MM/yy hh:MM")</div>
                </a>
            }
        </div>
    }
    else
    {
        <p>Take a Coffee. You have no pendding tasks.</p>
    }
</section>